// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package naming;

public final class ServiceRegistry_Stub
    extends java.rmi.server.RemoteStub
    implements naming.Registry
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_lookup_0;
    private static java.lang.reflect.Method $method_register_1;
    
    static {
	try {
	    $method_lookup_0 = naming.Registry.class.getMethod("lookup", new java.lang.Class[] {java.lang.String.class});
	    $method_register_1 = naming.Registry.class.getMethod("register", new java.lang.Class[] {java.lang.String.class, service.ServiceStub.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public ServiceRegistry_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of lookup(String)
    public service.ServiceStub lookup(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_lookup_0, new java.lang.Object[] {$param_String_1}, 1220707328721360832L);
	    return ((service.ServiceStub) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of register(String, ServiceStub)
    public void register(java.lang.String $param_String_1, service.ServiceStub $param_ServiceStub_2)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_register_1, new java.lang.Object[] {$param_String_1, $param_ServiceStub_2}, -8500161119354040002L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
